export const ErrorCode = {
  // Client errors
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // Auth
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Rate limiting
  RATE_LIMITED: 'RATE_LIMITED',

  // CAPTCHA
  CAPTCHA_MISSING: 'CAPTCHA_MISSING',
  CAPTCHA_FAILED: 'CAPTCHA_FAILED',
  CAPTCHA_ERROR: 'CAPTCHA_ERROR',

  // Database
  DUPLICATE: 'DUPLICATE',
  FK_VIOLATION: 'FK_VIOLATION',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Client-only (no server response)
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',
  UNKNOWN: 'UNKNOWN',
};
